### ISSUE TITLE
Upgrade to InfluxDB 0.9

### ISSUE THREAD

**Issue by daoshengmu** [mozilla-b2g/mozbench#35]
@dminor . I have upgrade the schema to 0.9 version, https://github.com/daoshengmu/mozbench/tree/influxDB_0.9. It is different a lot and can't be migrated from 0.8 directly. Please pay attention if it would bring any pain for the current version.

@TheKK please help me take a look at it as well.

**Comment by daoshengmu** [comment]
@dminor . As our discussions, I move some data from measurement name to tags. I think the schema would be like below.
 
Origin,
```
series = 'benchmarks.octane.Richards.mac.firefox.nightly'
'columns': ['value','browser-version', 'os-version', 'processor'],
'points': [[33390, 44.0, OS X 10.10.5, x86_64]]
```

To this version for supporting 0.9,
```
benchmarks,bench-name=octane,name=Richards,device=mac,platform=mac,browser-name=firefox.nightly,os-version=OS\ X\ 10.10.5,processor=x86_64 value=27638 1445326023131261184
```

How do you think?

**Comment by dminor** [comment]
This looks ok to me.
